#!/bin/bash

rm -fr tmpdir
mkdir -p tmpdir/scans
chmod gao+rwx tmpdir
chmod gao+rwx tmpdir/scans

sqlite3 tmpdir/students.db < schemas.sql
chmod gao+rw tmpdir/students.db

php-cgi grade.php go=upload tool="Upload Scans" file="scans-1.PDF" input="num=2"
php-cgi grade.php go=upload tool=Roster file="students.txt"

sqlite3 tmpdir/students.db < print.sql 

